# fly.toml app configuration file generated for phoenix-liveview-calculator on 2024-11-28T19:12:57Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phoenix-liveview-calculator'
primary_region = 'lhr'
kill_signal = 'SIGTERM'

[build]

[env]
  PHX_HOST = 'phoenix-liveview-calculator.fly.dev'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 1000

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
